name: Keep Render App Alive

on:
  schedule:
    - cron: "*/10 * * * *" # Runs every 10 minutes
  workflow_dispatch: # Allows manual triggering from GitHub UI

jobs:
  ping:
    name: Ping Render App
    runs-on: ubuntu-latest
    steps:
      - name: Send HTTP Request
        id: ping
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.RENDER_APP_URL }}
          method: "GET"
          timeout: 5000

      - name: Log Response
        run: |
          echo "Response Status: ${{ steps.ping.outputs.status }}"
          echo "Response Body: ${{ steps.ping.outputs.response }}"

      - name: Check Response
        if: ${{ steps.ping.outputs.status >= 400 }} # Only fail on actual error status codes
        uses: actions/github-script@v6
        with:
          script: |
            core.setFailed('Ping failed with status: ${{ steps.ping.outputs.status }}')
